import type { Metadata } from "next";
import { ThemeProvider } from "./theme-provider";
import Nav from "../components/nav";
import Footer from "../components/footer";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import "./styles/globals.css";
import "./styles/scrollbar.css";
import { TooltipProvider } from "@radix-ui/react-tooltip";
import Header from "@/components/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${GeistSans.variable} ${GeistMono.variable}`}
      // style={{ paddingLeft: "calc(100vw - 100%)" }}
    >
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="bg-background relative flex flex-col min-h-screen pt-[4.5rem]">
            <Nav />
            {children}
            <Footer />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
